check:
  - thoth-build
build:
  build-stratergy: "Dockerfile"
  dockerfile-path: "build/Dockerfile.multistage"
  custom-tag: "latest"
  registry: "quay.io"
  registry-org: "modh"
  registry-project: "opendatahub-operator"
  registry-secret: "modh-pusher-secret"
